# Generated by Django 4.1.2 on 2022-10-30 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=70, unique=True)),
                ('slug', models.SlugField(max_length=70)),
                ('imagem', models.CharField(blank=True, max_length=70)),
                ('sinopse', models.CharField(max_length=1500)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genero.genero')),
            ],
            options={
                'db_table': 'livros',
            },
        ),
    ]
