# Generated by Django 4.1.4 on 2022-12-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
