# Generated by Django 4.1.4 on 2022-12-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livros_autor_livros_cep_livros_isbn_livros_rua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='isbn',
        ),
    ]
