# Generated by Django 4.1.4 on 2022-12-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_remove_livros_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='rua',
        ),
    ]
