# Generated by Django 4.1.4 on 2022-12-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_remove_livros_autor_remove_livros_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='autor',
            field=models.CharField(default=123, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='cep',
            field=models.CharField(default=123, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='isbn',
            field=models.CharField(default=123, max_length=70, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='rua',
            field=models.CharField(default=123, max_length=70),
            preserve_default=False,
        ),
    ]
