# Generated by Django 4.1.4 on 2022-12-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_livros_autor_livros_cep_livros_isbn_livros_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='quantidade',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
