# Generated by Django 4.1.4 on 2022-12-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_livros_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='rua',
        ),
    ]
