# Generated by Django 4.1.4 on 2022-12-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_remove_livros_cep_remove_livros_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='cep',
            field=models.CharField(default=123, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='rua',
            field=models.CharField(default=123, max_length=70),
            preserve_default=False,
        ),
    ]
